/gun/momentumAmp 0.006222 keV
/detector/targetWidth 1.5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.01823053 keV
/detector/targetWidth 0.00045
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.032928 keV
/detector/targetWidth 0.00038
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.0355644 keV
/detector/targetWidth 0.000385
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.04340198 keV
/detector/targetWidth 0.0004
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.05667876 keV
/detector/targetWidth 0.00045
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.078642 keV
/detector/targetWidth 0.00014
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.10201505 keV
/detector/targetWidth 3e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.10669862 keV
/detector/targetWidth 3.2e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.11159722 keV
/detector/targetWidth 3.2e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.11730431 keV
/detector/targetWidth 3.2e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.12268982 keV
/detector/targetWidth 3.2e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.12832258 keV
/detector/targetWidth 3.2e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.13421395 keV
/detector/targetWidth 3.2e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.14037579 keV
/detector/targetWidth 3.6e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.14682052 keV
/detector/targetWidth 3.6e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.15356113 keV
/detector/targetWidth 3.8e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.16061121 keV
/detector/targetWidth 4e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.16798497 keV
/detector/targetWidth 4.4e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.17569726 keV
/detector/targetWidth 5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.18468244 keV
/detector/targetWidth 5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.19316131 keV
/detector/targetWidth 5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.20202946 keV
/detector/targetWidth 5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.21130475 keV
/detector/targetWidth 5.5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.22100588 keV
/detector/targetWidth 5.5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.23115238 keV
/detector/targetWidth 6.5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.24176472 keV
/detector/targetWidth 7.5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.25035448 keV
/detector/targetWidth 7.5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.25924942 keV
/detector/targetWidth 8.5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.27115171 keV
/detector/targetWidth 9.5e-05
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.28501845 keV
/detector/targetWidth 0.0001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.29810381 keV
/detector/targetWidth 0.00011
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.31178993 keV
/detector/targetWidth 0.00012
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.32610438 keV
/detector/targetWidth 0.00013
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.34107602 keV
/detector/targetWidth 0.00016
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.35673502 keV
/detector/targetWidth 0.00017
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.37311293 keV
/detector/targetWidth 0.00018
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.39024276 keV
/detector/targetWidth 0.0002
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.40815904 keV
/detector/targetWidth 0.00024
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.42477688 keV
/detector/targetWidth 0.00025
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.4442756 keV
/detector/targetWidth 0.0003
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.46467255 keV
/detector/targetWidth 0.00035
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.48600594 keV
/detector/targetWidth 0.0004
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.50327344 keV
/detector/targetWidth 0.0004
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.52637901 keV
/detector/targetWidth 0.00045
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.55054538 keV
/detector/targetWidth 0.00052
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.57582123 keV
/detector/targetWidth 0.0006
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.59627982 keV
/detector/targetWidth 0.0006
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.62365537 keV
/detector/targetWidth 0.0007
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.65228775 keV
/detector/targetWidth 0.0008
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.68564583 keV
/detector/targetWidth 0.001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.71712423 keV
/detector/targetWidth 0.001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.75004781 keV
/detector/targetWidth 0.0012
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.78448294 keV
/detector/targetWidth 0.0012
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.82049901 keV
/detector/targetWidth 0.0015
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.85816859 keV
/detector/targetWidth 0.0015
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.89756761 keV
/detector/targetWidth 0.0018
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.93877546 keV
/detector/targetWidth 0.0022
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 0.98187519 keV
/detector/targetWidth 0.0028
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.0269536 keV
/detector/targetWidth 0.003
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.0794722 keV
/detector/targetWidth 0.0033
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.1290314 keV
/detector/targetWidth 0.0037
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.1808659 keV
/detector/targetWidth 0.0043
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.2350801 keV
/detector/targetWidth 0.0048
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.2917833 keV
/detector/targetWidth 0.0051
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.3510899 keV
/detector/targetWidth 0.0061
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.4131192 keV
/detector/targetWidth 0.0068
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.4779963 keV
/detector/targetWidth 0.0073
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.545852 keV
/detector/targetWidth 0.0082
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.6168229 keV
/detector/targetWidth 0.00082
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.6995075 keV
/detector/targetWidth 0.00087
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.7775328 keV
/detector/targetWidth 0.00098
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.8406875 keV
/detector/targetWidth 0.0011
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.906086 keV
/detector/targetWidth 0.00125
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 1.9935955 keV
/detector/targetWidth 0.0014
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.0851227 keV
/detector/targetWidth 0.0016
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.1808519 keV
/detector/targetWidth 0.0017
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.2786505 keV
/detector/targetWidth 0.00185
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.3620177 keV
/detector/targetWidth 0.0022
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.4704593 keV
/detector/targetWidth 0.00235
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.5781443 keV
/detector/targetWidth 0.0001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.6890617 keV
/detector/targetWidth 0.0001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.812518 keV
/detector/targetWidth 0.0001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 2.9124451 keV
/detector/targetWidth 0.0001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 3.0461571 keV
/detector/targetWidth 0.0001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 3.186008 keV
/detector/targetWidth 0.0005
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 3.3322794 keV
/detector/targetWidth 0.0005
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 3.4852663 keV
/detector/targetWidth 0.0005
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 3.6452769 keV
/detector/targetWidth 0.0005
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 3.8126337 keV
/detector/targetWidth 0.0005
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 4.055024 keV
/detector/targetWidth 0.0005
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 7.392525 keV
/detector/targetWidth 0.0005
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 10.32004 keV
/detector/targetWidth 0.001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 11.8578 keV
/detector/targetWidth 0.001
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 16.46362 keV
/detector/targetWidth 0.01
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 30.01405 keV
/detector/targetWidth 0.01
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 54.71721 keV
/detector/targetWidth 0.1
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 71.45536 keV
/detector/targetWidth 0.1
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 130.2669 keV
/detector/targetWidth 0.5
/run/reinitializeGeometry
/run/beamOn 10000


/gun/momentumAmp 237.4835 keV
/detector/targetWidth 1.0
/run/reinitializeGeometry
/run/beamOn 10000



