# Archivo .mac para energías en el rango 6 - 20 keV

/gun/energy 6.051453 keV
/run/beamOn 3000

/gun/energy 6.469004 keV
/run/beamOn 3000

/gun/energy 6.915365 keV
/run/beamOn 3000

/gun/energy 7.392525 keV
/run/beamOn 3000

/gun/energy 7.902609 keV
/run/beamOn 3000

/gun/energy 8.44789 keV
/run/beamOn 3000

/gun/energy 9.030794 keV
/run/beamOn 3000

/gun/energy 9.653919 keV
/run/beamOn 3000

/gun/energy 10.00266 keV
/run/beamOn 3000

/gun/energy 10.15577 keV
/run/beamOn 3000

/gun/energy 10.19659 keV
/run/beamOn 3000

/gun/energy 10.25783 keV
/run/beamOn 3000

/gun/energy 10.32004 keV
/run/beamOn 3000

/gun/energy 10.41094 keV
/run/beamOn 3000

/gun/energy 11.03212 keV
/run/beamOn 3000

/gun/energy 11.31312 keV
/run/beamOn 3000

/gun/energy 11.48628 keV
/run/beamOn 3000

/gun/energy 11.53246 keV
/run/beamOn 3000

/gun/energy 11.60172 keV
/run/beamOn 3000

/gun/energy 11.77488 keV
/run/beamOn 3000

/gun/energy 11.79334 keV
/run/beamOn 3000

/gun/energy 11.8578 keV
/run/beamOn 3000

/gun/energy 12.0393 keV
/run/beamOn 3000

/gun/energy 12.0877 keV
/run/beamOn 3000

/gun/energy 12.1603 keV
/run/beamOn 3000

/gun/energy 12.3418 keV
/run/beamOn 3000

/gun/energy 12.60708 keV
/run/beamOn 3000

/gun/energy 13.47697 keV
/run/beamOn 3000

/gun/energy 14.40688 keV
/run/beamOn 3000

/gun/energy 15.40095 keV
/run/beamOn 3000

/gun/energy 16.46362 keV
/run/beamOn 3000

/gun/energy 17.59961 keV
/run/beamOn 3000

/gun/energy 18.81398 keV
/run/beamOn 3000

